---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-{{ .Values.namespacePermissions.user }}
  namespace: {{ .Values.demoNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namespacePermissions.role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.namespacePermissions.user }}
