---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    {{- if eq .Values.deploymentStrategy.type "RollingUpdate" }}
    {{- with .Values.deploymentStrategy }}
    rollingUpdate:
      maxSurge: {{ .rollingMaxSurge }}
      maxUnavailable: {{ .rollingMaxUnavailable }}
    {{- end }}
    {{- end }}
    {{- if eq .Values.deploymentStrategy.type "Recreate" }}
    recreateParams:
      timeoutSeconds: {{ .Values.deploymentStrategy.timeout }}
    {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deployment: {{ .Values.applicationName }}
  template:
    metadata:
      name: {{ .Values.applicationName }}
      labels:
        deployment: {{ .Values.applicationName }}
        app: {{ .Values.applicationName }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod | default 60 }}
      containers:
      - name: {{ .Values.applicationName }}
        image: '{{ .Values.image.registry }}/{{ .Values.image.account }}/{{ .Values.image.repository }}:{{ .Values.version }}'
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        resources: {{ if not .Values.limits}}{}{{end}}
          {{- if .Values.limits }}
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
          {{- end }}
          {{- if .Values.requests }}
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}
          {{- end }}
        {{- with .Values.health }}
        readinessProbe:
         httpGet:
           path: {{ .readinessEndpoint }}
           port: {{ $.Values.port }}
         initialDelaySeconds: {{ .probeDelay }}
         timeoutSeconds: {{ .probeTimeout }}
        livenessProbe:
         httpGet:
           path: {{ .livenessEndpoint }}
           port: {{ $.Values.port }}
         periodSeconds: {{ .probePeriod }}
         initialDelaySeconds: {{ .probeDelay }}
         timeoutSeconds: {{ .probeTimeout }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.applicationName }}-secret-volume
          mountPath: /opt/jws-5.6/tomcat/lib/persistence.properties
          subPath: persistence.properties
      volumes:
      - name: {{ .Values.applicationName }}-secret-volume
        secret:
          secretName: {{ .Values.applicationName }}-secret
          items:
            - key: persistence.properties
              path: persistence.properties
